# Generated by Django 5.2.10 on 2026-01-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='orderid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
