# Generated by Django 5.2.10 on 2026-01-30 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_orderdetails_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=150)),
                ('showtime', models.CharField(max_length=100)),
                ('screenname', models.CharField(max_length=100)),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
